/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Building-7lMEpT2ICD.glb -t -T -o ../../src/models/Building-7lMEpT2ICD.tsx 
Files: Building-7lMEpT2ICD.glb [91.47KB] > /Users/user/Desktop/Projects/geesehacks/src/models/Building-7lMEpT2ICD-transformed.glb [16.17KB] (82%)
*/

import type * as THREE from 'three'
import type { GLTF } from 'three-stdlib'
import { useGLTF } from '@react-three/drei'

// Define GLTFAction type
type GLTFAction = THREE.AnimationClip

type GLTFResult = GLTF & {
  nodes: {
    building_D: THREE.Mesh
  }
  materials: {
    citybits_texture: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Building-7lMEpT2ICD-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.building_D.geometry} material={materials.citybits_texture} scale={100} />
    </group>
  )
}

useGLTF.preload('/models/Building-7lMEpT2ICD-transformed.glb')
