/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Building.glb -t -T -o ../../src/models/Building.tsx 
Files: Building.glb [71.56KB] > /Users/user/Desktop/Projects/geesehacks/src/models/Building-transformed.glb [15.48KB] (78%)
*/

import type * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

// Define GLTFAction type
type GLTFAction = THREE.AnimationClip

type GLTFResult = GLTF & {
  nodes: {
    building_A: THREE.Mesh
  }
  materials: {
    citybits_texture: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Building-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.building_A.geometry} material={materials.citybits_texture} scale={100} />
    </group>
  )
}

useGLTF.preload('/models/Building-transformed.glb')
