/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Building-qOhhGLftam.glb -t -T -o ../../src/models/Building-qOhhGLftam.tsx 
Files: Building-qOhhGLftam.glb [106.98KB] > /Users/user/Desktop/Projects/geesehacks/src/models/Building-qOhhGLftam-transformed.glb [17.95KB] (83%)
*/

import type * as THREE from 'three'
import type { GLTF } from 'three-stdlib'
import { useGLTF } from '@react-three/drei'

// Define GLTFAction type
type GLTFAction = THREE.AnimationClip

type GLTFResult = GLTF & {
  nodes: {
    building_E: THREE.Mesh
  }
  materials: {
    citybits_texture: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Building-qOhhGLftam-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.building_E.geometry} material={materials.citybits_texture} scale={100} />
    </group>
  )
}

useGLTF.preload('/models/Building-qOhhGLftam-transformed.glb')