/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cartoon_buildings.glb --transform --types 
Files: cartoon_buildings.glb [10.28MB] > /Users/user/Desktop/Projects/geesehacks/public/cartoon_buildings-transformed.glb [969.96KB] (91%)
*/

import type * as THREE from 'three'
import type { GLTF } from 'three-stdlib'
import { useGLTF } from '@react-three/drei'

type GLTFAction = THREE.AnimationClip

type GLTFResult = GLTF & {
  nodes: {
    Cube005: THREE.Mesh
    Cube005_1: THREE.Mesh
    b_house01_L: THREE.Mesh
    road008: THREE.Mesh
  }
  materials: {
    mat_level1_main: THREE.MeshStandardMaterial
    mat_level1_second: THREE.MeshStandardMaterial
    mat_building_03_detail: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/cartoon_buildings-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-19.338, 0, 2.5]} rotation={[0, -0.013, 0]} scale={1.28}>
        <mesh geometry={nodes.Cube005.geometry} material={materials.mat_level1_main} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials.mat_level1_second} />
      </group>
      <mesh geometry={nodes.b_house01_L.geometry} material={materials.mat_building_03_detail} position={[-48.513, 0, 1.398]} rotation={[0, -0.013, 0]} />
      <mesh geometry={nodes.road008.geometry} material={nodes.road008.material} position={[26.906, 0, 33.011]} />
    </group>
  )
}

useGLTF.preload('/models/cartoon_buildings-transformed.glb')