/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 city.glb --transform --types 
Files: city.glb [2.04MB] > /Users/user/Desktop/Projects/geesehacks/public/city-transformed.glb [71.79KB] (96%)
*/

import type * as THREE from 'three'
import type { GLTF } from 'three-stdlib'
import { useGLTF } from '@react-three/drei'

// Define GLTFAction type
type GLTFAction = THREE.AnimationClip

type GLTFResult = GLTF & {
  nodes: {
    group2014698194: THREE.Mesh
    group1354432531: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/city-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group2014698194.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.group1354432531.geometry} material={materials.PaletteMaterial002} />
    </group>
  )
}

useGLTF.preload('/models/city-transformed.glb')
