/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 city_model.glb --transform --types 
Files: city_model.glb [9.39MB] > /Users/user/Desktop/Projects/geesehacks/public/city_model-transformed.glb [483.58KB] (95%)
*/

import type * as THREE from 'three'
import type { GLTF } from 'three-stdlib'
import { useGLTF } from '@react-three/drei'

type GLTFAction = THREE.AnimationClip
type GLTFResult = GLTF & {
  nodes: {
    SketchfabCity_PolygonMiniCity_01_0: THREE.Mesh
    SketchfabCity_PolygonMiniCity_01_Blue_0: THREE.Mesh
    SketchfabCity_PolygonMiniCity_01_Red_0: THREE.Mesh
    SketchfabCity_PolygonMiniCity_01_Yellow_0: THREE.Mesh
    SketchfabCity_Water_0: THREE.Mesh
  }
  materials: {
    PolygonMiniCity_01: THREE.MeshStandardMaterial
    PolygonMiniCity_01_Blue: THREE.MeshStandardMaterial
    PolygonMiniCity_01_Red: THREE.MeshStandardMaterial
    PolygonMiniCity_01_Yellow: THREE.MeshStandardMaterial
    Water: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/city_model-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SketchfabCity_PolygonMiniCity_01_0.geometry} material={materials.PolygonMiniCity_01} position={[3.653, -0.178, -2.635]} />
      <mesh geometry={nodes.SketchfabCity_PolygonMiniCity_01_Blue_0.geometry} material={materials.PolygonMiniCity_01_Blue} position={[3.653, -0.178, -2.635]} />
      <mesh geometry={nodes.SketchfabCity_PolygonMiniCity_01_Red_0.geometry} material={materials.PolygonMiniCity_01_Red} position={[3.653, -0.178, -2.635]} />
      <mesh geometry={nodes.SketchfabCity_PolygonMiniCity_01_Yellow_0.geometry} material={materials.PolygonMiniCity_01_Yellow} position={[3.653, -0.178, -2.635]} />
      <mesh geometry={nodes.SketchfabCity_Water_0.geometry} material={materials.Water} position={[3.653, -0.178, -2.635]} />
    </group>
  )
}

useGLTF.preload('/models/city_model-transformed.glb')
