/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Streetlight.glb -t -T -o ../../src/models/Streetlight.tsx 
Files: Streetlight.glb [29.15KB] > /Users/user/Desktop/Projects/geesehacks/src/models/Streetlight-transformed.glb [10.76KB] (63%)
*/

import type * as THREE from 'three'
import type { GLTF } from 'three-stdlib'
import { useGLTF } from '@react-three/drei'

// Define GLTFAction type
type GLTFAction = THREE.AnimationClip

type GLTFResult = GLTF & {
  nodes: {
    streetlight: THREE.Mesh
  }
  materials: {
    citybits_texture: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Streetlight-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.streetlight.geometry} material={materials.citybits_texture} scale={100} />
    </group>
  )
}

useGLTF.preload('/models/Streetlight-transformed.glb')