/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Traffic light-Q6k7Izx6YD.glb -t -T -o ../../src/models/Traffic light-Q6k7Izx6YD.tsx 
Files: Traffic light-Q6k7Izx6YD.glb [52.68KB] > /Users/user/Desktop/Projects/geesehacks/src/models/Traffic light-Q6k7Izx6YD-transformed.glb [13.61KB] (74%)
*/

import type * as THREE from 'three'
import type { GLTF } from 'three-stdlib'
import { useGLTF } from '@react-three/drei'

// Define GLTFAction type
type GLTFAction = THREE.AnimationClip

type GLTFResult = GLTF & {
  nodes: {
    trafficlight_A: THREE.Mesh
  }
  materials: {
    citybits_texture: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Traffic light-Q6k7Izx6YD-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.trafficlight_A.geometry} material={materials.citybits_texture} scale={100} />
    </group>
  )
}

useGLTF.preload('/models/Traffic light-Q6k7Izx6YD-transformed.glb')